In [6]:
import pandas as pd
from sqlalchemy import create_engine
!pip install psycopg2-binary
import psycopg2
import datetime
import numpy as np

Requirement already satisfied: psycopg2-binary in c:\users\usuario\anaconda3\lib\site-packages (2.9.6)

In [ ]:
### dados importantes para levantar a análise ###

# grid - posição de largada
# position - rank final

# results.csv -> raceId, driverId, grid, positionOrder
# pit_stops.csv -> raceId, driverId, stop, duration(seconds)
# drivers.csv -> driverId, forename, surname 
# races.csv -> raceId, circuitId, name(circuit name), date

# primeiro: Filtrar os dados apenas em 1 circuito (Interlagos -> circuitId = 18)
# com o pit_stops: MÉDIA DO TEMPO DE PITSTOP POR PILOTO (driverId) em cada corrida
# modelo de classificação/classificatorio

## Lendo e Limpando os dados

In [2]:
results = pd.read_csv('./results.csv')
drivers = pd.read_csv('./drivers.csv')
races = pd.read_csv('./races.csv')
pit_stops = pd.read_csv('./pit_stops.csv')

In [3]:
for column in results.columns:
    if column not in ['raceId', 'driverId', 'grid', 'positionOrder']:
        results = results.drop(column, axis=1)
print('Results')
results

Results

       raceId  driverId  grid  positionOrder
0          18         1     1              1
1          18         2     5              2
2          18         3     7              3
3          18         4    11              4
4          18         5     3              5
...       ...       ...   ...            ...
25835    1096       854    12             16
25836    1096       825    16             17
25837    1096         1     5             18
25838    1096       849    20             19
25839    1096         4    10             20

[25840 rows x 4 columns]

In [4]:
for column in pit_stops.columns:
    if column not in ['raceId', 'driverId', 'stop', 'lap', 'duration']:
        pit_stops = pit_stops.drop(column, axis=1)
print('Pit Stops')
pit_stops

Pit Stops

      raceId  driverId  stop  lap duration
0        841       153     1    1   26.898
1        841        30     1    1   25.021
2        841        17     1   11   23.426
3        841         4     1   12   23.251
4        841        13     1   13   23.842
...      ...       ...   ...  ...      ...
9629    1096       849     2   38   25.174
9630    1096       840     2   40   21.802
9631    1096       839     2   41   21.734
9632    1096       846     2   42   21.559
9633    1096       855     2   44   23.159

[9634 rows x 5 columns]

In [5]:
for column in drivers.columns:
    if column not in ['driverId', 'forename', 'surname']:
        drivers = drivers.drop(column, axis=1)
print('Drivers')
drivers.sample(3)

Drivers

     driverId  forename   surname
98         99  Gabriele  Tarquini
119       120  Fabrizio  Barbazza
578       578      Mike  Hawthorn

In [6]:
for column in races.columns:
    if column not in ['raceId', 'circuitId', 'name', 'date']:
        races = races.drop(column, axis=1)
print('Races')
races.sample(3)

Races

     raceId  circuitId                      name        date
641     642         46  United States Grand Prix  1971-10-03
348     349         13        Belgian Grand Prix  2010-08-29
214     215          9        British Grand Prix  1997-07-13

## Criando conexão com o DB e salvando os DataFrames

In [8]:
'tipo_de_banco_de_dados://usuario:senha@endereco_do_servidor:porta/nome_do_banco_de_dados'
engine = create_engine('postgresql://root:root@localhost:5432/dbanalise')

# df_dimensoes.to_sql('nome_da_tabela_dimensoes', con=engine, if_exists='replace', index=False)
# df_medidas.to_sql('nome_da_tabela_fato', con=engine, if_exists='replace', index=False)

In [9]:
results.to_sql('fato_resultados', con=engine, if_exists='replace', index=False)
pit_stops.to_sql('fato_pit_stops', con=engine, if_exists='replace', index=False)
drivers.to_sql('dimensao_pilotos', con=engine, if_exists='replace', index=False)
races.to_sql('dimensao_corridas', con=engine, if_exists='replace', index=False)

102

## Query no banco para pegar o DataFrame base do projeto

In [53]:
# recuperar uma tabela através de SELECT JOIN... juntando as tabelas com seus id's referentes

# races + pit_stops -> 'raceId': result1 #
# result1 + driver -> 'driverId': result2
# result2 + results -> 'driverId ou raceId': finalResult
conn = psycopg2.connect(dbname="dbanalise", user="root", password="root")
cur = conn.cursor()

# query = '''
# SELECT *
# FROM dimensao_corridas c
# INNER JOIN fato_pit_stops ps ON ps."raceId" = c."raceId"
# INNER JOIN dimensao_pilotos dp ON dp."driverId" = ps."driverId"
# INNER JOIN fato_resultados r ON r."raceId" = c."raceId"
# WHERE c."circuitId" = 18
# '''

query = '''
SELECT *
FROM fato_resultados
INNER JOIN dimensao_corridas ON fato_resultados."raceId" = dimensao_corridas."raceId"
INNER JOIN dimensao_pilotos ON dimensao_pilotos."driverId" = fato_resultados."driverId"
INNER JOIN fato_pit_stops ON fato_resultados."raceId" = fato_pit_stops."raceId" AND fato_resultados."driverId" = fato_pit_stops."driverId"
WHERE dimensao_corridas."circuitId" = 18
'''
cur.execute(query)

rows = cur.fetchall()

cur.close()
conn.close()

finalColumns = ['raceId', 'driverId', 'grid', 'positionOrder', 'raceId1', 'circuitId', 'name', 'date', 'driverId1', 'forename', 'surname', 'raceId1', 'driverId1', 'stop', 'lap', 'duration' ]

df_result = pd.DataFrame(rows, columns=finalColumns)
df_result

,raceId,driverId,grid,positionOrder,raceId1,circuitId,name,date,driverId1,forename,surname,raceId1,driverId1,stop,lap,duration
0,859,30,10,15,859,18,Brazilian Grand Prix,2011-11-27,30,Michael,Schumacher,859,30,1,10,25.481
1,859,811,9,17,859,18,Brazilian Grand Prix,2011-11-27,811,Bruno,Senna,859,811,1,12,21.900
2,859,808,15,10,859,18,Brazilian Grand Prix,2011-11-27,808,Vitaly,Petrov,859,808,1,13,21.169
3,859,16,8,6,859,18,Brazilian Grand Prix,2011-11-27,16,Adrian,Sutil,859,16,1,14,21.097
4,859,18,3,3,859,18,Brazilian Grand Prix,2011-11-27,18,Jenson,Button,859,18,1,15,22.005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
594,1095,4,17,5,1095,18,Brazilian Grand Prix,2022-11-13,4,Fernando,Alonso,1095,4,3,52,23.790
595,1095,842,10,14,1095,18,Brazilian Grand Prix,2022-11-13,842,Pierre,Gasly,1095,842,3,52,23.009
596,1095,832,7,3,1095,18,Brazilian Grand Prix,2022-11-13,832,Carlos,Sainz,1095,832,3,53,23.816
597,1095,849,18,16,1095,18,Brazilian Grand Prix,2022-11-13,849,Nicholas,Latifi,1095,849,3,52,23.640
598,1095,852,0,17,1095,18,Brazilian Grand Prix,2022-11-13,852,Yuki,Tsunoda,1095,852,3,54,23.635

In [54]:
# tirando as colunas repetidas
df_result = df_result.drop('raceId1', axis=1)
df_result = df_result.drop('driverId1', axis=1)
df_result

,raceId,driverId,grid,positionOrder,circuitId,name,date,forename,surname,stop,lap,duration
0,859,30,10,15,18,Brazilian Grand Prix,2011-11-27,Michael,Schumacher,1,10,25.481
1,859,811,9,17,18,Brazilian Grand Prix,2011-11-27,Bruno,Senna,1,12,21.900
2,859,808,15,10,18,Brazilian Grand Prix,2011-11-27,Vitaly,Petrov,1,13,21.169
3,859,16,8,6,18,Brazilian Grand Prix,2011-11-27,Adrian,Sutil,1,14,21.097
4,859,18,3,3,18,Brazilian Grand Prix,2011-11-27,Jenson,Button,1,15,22.005
...,...,...,...,...,...,...,...,...,...,...,...,...
594,1095,4,17,5,18,Brazilian Grand Prix,2022-11-13,Fernando,Alonso,3,52,23.790
595,1095,842,10,14,18,Brazilian Grand Prix,2022-11-13,Pierre,Gasly,3,52,23.009
596,1095,832,7,3,18,Brazilian Grand Prix,2022-11-13,Carlos,Sainz,3,53,23.816
597,1095,849,18,16,18,Brazilian Grand Prix,2022-11-13,Nicholas,Latifi,3,52,23.640
598,1095,852,0,17,18,Brazilian Grand Prix,2022-11-13,Yuki,Tsunoda,3,54,23.635

## Convertendo a coluan 'duration' para float, para futuras manipulações

In [55]:
import pandas as pd
import datetime

# Função para converter a string de tempo para float
def convert_duration(time_str):
    try:
        time_obj = datetime.datetime.strptime(time_str, '%M:%S.%f')
    except ValueError:
        time_obj = datetime.datetime.strptime(time_str, '%S.%f')
    total_seconds = time_obj.minute * 60 + time_obj.second + time_obj.microsecond / 1e6
    return total_seconds

# Aplicando a função de conversão à coluna 'duration'
df_result['duration'] = df_result['duration'].apply(convert_duration).astype(float)

In [56]:
df_result.duration.dtype

dtype('float64')

## Verificando os dados (media, desvio padrão da duração de pit_stops)

In [57]:
df_result

,raceId,driverId,grid,positionOrder,circuitId,name,date,forename,surname,stop,lap,duration
0,859,30,10,15,18,Brazilian Grand Prix,2011-11-27,Michael,Schumacher,1,10,25.481
1,859,811,9,17,18,Brazilian Grand Prix,2011-11-27,Bruno,Senna,1,12,21.900
2,859,808,15,10,18,Brazilian Grand Prix,2011-11-27,Vitaly,Petrov,1,13,21.169
3,859,16,8,6,18,Brazilian Grand Prix,2011-11-27,Adrian,Sutil,1,14,21.097
4,859,18,3,3,18,Brazilian Grand Prix,2011-11-27,Jenson,Button,1,15,22.005
...,...,...,...,...,...,...,...,...,...,...,...,...
594,1095,4,17,5,18,Brazilian Grand Prix,2022-11-13,Fernando,Alonso,3,52,23.790
595,1095,842,10,14,18,Brazilian Grand Prix,2022-11-13,Pierre,Gasly,3,52,23.009
596,1095,832,7,3,18,Brazilian Grand Prix,2022-11-13,Carlos,Sainz,3,53,23.816
597,1095,849,18,16,18,Brazilian Grand Prix,2022-11-13,Nicholas,Latifi,3,52,23.640
598,1095,852,0,17,18,Brazilian Grand Prix,2022-11-13,Yuki,Tsunoda,3,54,23.635

In [58]:
# media de duração dos pit_stops de cada piloto por corrida (no circuito de Interlagos)

# media de durações de cada piloto em cada corrida
mediasPilotoCorrida = df_result.groupby(['driverId', 'raceId', 'forename', 'surname']).agg({'duration': [np.mean]}).reset_index()
mediasPilotoCorrida.head(7)

  driverId raceId forename   surname     duration
                                             mean
0        1    859    Lewis  Hamilton    20.725333
1        1    879    Lewis  Hamilton    23.008000
2        1    899    Lewis  Hamilton    21.487667
3        1    917    Lewis  Hamilton    23.483000
4        1    944    Lewis  Hamilton    23.470667
5        1    967    Lewis  Hamilton  1746.204500
6        1    987    Lewis  Hamilton    20.115000

In [59]:
# media de durações de cada piloto (em geral)
mediaGeralPilotos = mediasPilotoCorrida.groupby(['driverId', 'forename', 'surname']).agg({('duration', 'mean'): np.mean}).reset_index()
mediaGeralPilotos

   driverId  forename     surname    duration
                                         mean
0         1     Lewis    Hamilton  178.943106
1         3      Nico     Rosberg  310.315944
2         4  Fernando      Alonso  137.793942
3         5    Heikki  Kovalainen   23.601967
4         8      Kimi   Räikkönen   23.211464
..      ...       ...         ...         ...
58      849  Nicholas      Latifi   23.143708
59      852      Yuki     Tsunoda   23.893467
60      853    Nikita     Mazepin   20.002667
61      854      Mick  Schumacher   25.195350
62      855    Guanyu        Zhou   24.721500

[63 rows x 4 columns]

## Nota-se que alguns pilotos possuem uma médias altíssimas em determinadas corridas, o que afeta muito na média final.

In [60]:
desvioPadrao = df_result.groupby(by='raceId').agg({'duration': [np.std]})
desvioPadrao

          duration
               std
raceId
859       1.469963
879       3.415799
899       2.350852
917       2.344446
944       1.402216
967     879.815057
987       3.070186
1008      2.686992
1029      1.740983
1071      4.074517
1095      2.228754

### Ao calcular o desvio padrão das durações de pit_stops de cada corrida, nota-se que a corrida de id = 967 possui um valor muito alto comparado com os demais.

In [61]:
# corrida 967 com duração altíssima de pit_stops
df_result.query("raceId == 967 and duration > 30")

,raceId,driverId,grid,positionOrder,circuitId,name,date,forename,surname,stop,lap,duration
289,967,1,1,1,18,Brazilian Grand Prix,2016-11-13,Lewis,Hamilton,1,20,2010.361
290,967,3,2,2,18,Brazilian Grand Prix,2016-11-13,Nico,Rosberg,1,20,2009.747
291,967,830,4,3,18,Brazilian Grand Prix,2016-11-13,Max,Verstappen,2,20,2009.643
292,967,807,8,7,18,Brazilian Grand Prix,2016-11-13,Nico,Hülkenberg,1,20,2008.504
293,967,815,9,4,18,Brazilian Grand Prix,2016-11-13,Sergio,Pérez,1,20,2008.398
294,967,832,15,6,18,Brazilian Grand Prix,2016-11-13,Carlos,Sainz,1,20,2008.828
295,967,831,21,9,18,Brazilian Grand Prix,2016-11-13,Felipe,Nasr,1,20,2008.206
296,967,817,6,8,18,Brazilian Grand Prix,2016-11-13,Daniel,Ricciardo,2,20,2008.600
297,967,839,22,12,18,Brazilian Grand Prix,2016-11-13,Esteban,Ocon,1,20,2009.052
298,967,836,19,15,18,Brazilian Grand Prix,2016-11-13,Pascal,Wehrlein,1,20,2008.464
299,967,4,10,10,18,Brazilian Grand Prix,2016-11-13,Fernando,Alonso,2,20,2008.789
300,967,822,11,11,18,Brazilian Grand Prix,2016-11-13,Valtteri,Bottas,2,20,2008.595
301,967,825,18,14,18,Brazilian Grand Prix,2016-11-13,Kevin,Magnussen,2,20,2008.979
302,967,18,17,16,18,Brazilian Grand Prix,2016-11-13,Jenson,Button,2,20,2010.062
303,967,20,5,5,18,Brazilian Grand Prix,2016-11-13,Sebastian,Vettel,2,20,2010.637
304,967,13,13,18,18,Brazilian Grand Prix,2016-11-13,Felipe,Massa,2,20,2009.630
305,967,821,12,17,18,Brazilian Grand Prix,2016-11-13,Esteban,Gutiérrez,2,20,2011.147
306,967,826,14,13,18,Brazilian Grand Prix,2016-11-13,Daniil,Kvyat,3,20,2011.266
308,967,1,1,1,18,Brazilian Grand Prix,2016-11-13,Lewis,Hamilton,2,28,1482.048
309,967,3,2,2,18,Brazilian Grand Prix,2016-11-13,Nico,Rosberg,2,28,1481.624
310,967,830,4,3,18,Brazilian Grand Prix,2016-11-13,Max,Verstappen,3,28,1481.433
311,967,815,9,4,18,Brazilian Grand Prix,2016-11-13,Sergio,Pérez,2,28,1482.290
312,967,832,15,6,18,Brazilian Grand Prix,2016-11-13,Carlos,Sainz,2,28,1483.053
313,967,831,21,9,18,Brazilian Grand Prix,2016-11-13,Felipe,Nasr,2,28,1483.214
314,967,817,6,8,18,Brazilian Grand Prix,2016-11-13,Daniel,Ricciardo,3,28,1484.725
315,967,839,22,12,18,Brazilian Grand Prix,2016-11-13,Esteban,Ocon,2,28,1485.092
316,967,836,19,15,18,Brazilian Grand Prix,2016-11-13,Pascal,Wehrlein,2,28,1484.979
317,967,4,10,10,18,Brazilian Grand Prix,2016-11-13,Fernando,Alonso,3,28,1483.818
318,967,822,11,11,18,Brazilian Grand Prix,2016-11-13,Valtteri,Bottas,3,28,1483.957
319,967,825,18,14,18,Brazilian Grand Prix,2016-11-13,Kevin,Magnussen,3,28,1484.474
320,967,18,17,16,18,Brazilian Grand Prix,2016-11-13,Jenson,Button,3,28,1484.987
321,967,20,5,5,18,Brazilian Grand Prix,2016-11-13,Sebastian,Vettel,3,28,1483.923
322,967,807,8,7,18,Brazilian Grand Prix,2016-11-13,Nico,Hülkenberg,3,28,1485.304
323,967,13,13,18,18,Brazilian Grand Prix,2016-11-13,Felipe,Massa,3,28,1485.969
324,967,821,12,17,18,Brazilian Grand Prix,2016-11-13,Esteban,Gutiérrez,3,28,1484.444
325,967,826,14,13,18,Brazilian Grand Prix,2016-11-13,Daniil,Kvyat,4,28,1484.388


### Através de pesquisas, percebi que a corrida de id 967(2016 Brazilian Grand Prix) foi uma exceção, pois houve um delay de 35 minutos para depois restartar a corrida, então vamos desconsiderar esses registros.
[Fonte](https://en.wikipedia.org/wiki/2016_Brazilian_Grand_Prix)

### Iremos tratar esses dados desconsiderando os valores considerados outliers (pontos foras da curva).

In [62]:
# salvando os indices dessas corridas (corrida de id 967 e duração altíssima)
indices_para_remover = df_result.query("raceId == 967 and duration > 30").index.tolist()

In [63]:
df_result.drop(indices_para_remover, inplace=True)
df_result

,raceId,driverId,grid,positionOrder,circuitId,name,date,forename,surname,stop,lap,duration
0,859,30,10,15,18,Brazilian Grand Prix,2011-11-27,Michael,Schumacher,1,10,25.481
1,859,811,9,17,18,Brazilian Grand Prix,2011-11-27,Bruno,Senna,1,12,21.900
2,859,808,15,10,18,Brazilian Grand Prix,2011-11-27,Vitaly,Petrov,1,13,21.169
3,859,16,8,6,18,Brazilian Grand Prix,2011-11-27,Adrian,Sutil,1,14,21.097
4,859,18,3,3,18,Brazilian Grand Prix,2011-11-27,Jenson,Button,1,15,22.005
...,...,...,...,...,...,...,...,...,...,...,...,...
594,1095,4,17,5,18,Brazilian Grand Prix,2022-11-13,Fernando,Alonso,3,52,23.790
595,1095,842,10,14,18,Brazilian Grand Prix,2022-11-13,Pierre,Gasly,3,52,23.009
596,1095,832,7,3,18,Brazilian Grand Prix,2022-11-13,Carlos,Sainz,3,53,23.816
597,1095,849,18,16,18,Brazilian Grand Prix,2022-11-13,Nicholas,Latifi,3,52,23.640
598,1095,852,0,17,18,Brazilian Grand Prix,2022-11-13,Yuki,Tsunoda,3,54,23.635

### Com essas alterações, 'df_result' saiu de 599 registros para 563, uma mudança não tão significativa, porém importante para filtrar os dados considerados outliers

## Salva o DF obtido pela Query em um arquivo .csv, para usar posteriormente sem necessidade do DataBase

In [64]:
df_result.to_csv('Interlagos_infos.csv', index=False)